description: don't append wine to the default path settings
author: Michael Gilbert <mgilbert@debian.org>

--- a/Makefile.in
+++ b/Makefile.in
@@ -27,9 +27,9 @@ datarootdir     = @datarootdir@
 datadir         = @datadir@
 mandir          = @mandir@
 includedir      = @includedir@
-fontdir         = ${datadir}/wine/fonts
+fontdir         = /usr/share/wine/fonts
 nlsdir          = ${datadir}/wine/nls
-dlldir          = ${libdir}/wine
+dlldir          = ${libdir}
 top_srcdir      = @top_srcdir@
 top_builddir    = @top_builddir@
 srcdir          = @srcdir@
