description: don't append wine to the default path settings
author: Michael Gilbert <mgilbert@debian.org>
forwarded: not-needed

--- a/Makefile.in
+++ b/Makefile.in
@@ -27,9 +27,9 @@ datarootdir     = @datarootdir@
 datadir         = @datadir@
 mandir          = @mandir@
 includedir      = @includedir@
-fontdir         = ${datadir}/wine/fonts
+fontdir         = ${datadir}/wine
 nlsdir          = ${datadir}/wine/nls
-dlldir          = ${libdir}/wine
+dlldir          = ${libdir}
 srcdir          = @srcdir@
 SHELL           = /bin/sh
 ARCH            = @ARCH@
