# fake PE files and their corresponding ELF files
debian/tmp/usr/lib/*/*/*.*.so
debian/tmp/usr/lib/*/*/fakedlls

# ELF libraries
debian/tmp/usr/lib/*/*/ntdll.so
debian/tmp/usr/lib/*/*/gdi32.so
debian/tmp/usr/lib/*/*/bcrypt.so
debian/tmp/usr/lib/*/*/odbc32.so
debian/tmp/usr/lib/*/*/user32.so
debian/tmp/usr/lib/*/*/windowscodecs.so

# wine library
debian/tmp/usr/lib/*/*/libwine.so.*

# wine server
debian/tmp/wineserver usr/lib/wineVERSION

# configuration files
debian/tmp/usr/share/*/wine/*
